// DEPLOY-01: version every file the game loads by its content, so a browser can never combine cached old files with
// new ones. Run after changing anything in dist/ (tests/test-cache-deploy01.mjs fails until you do):
//
//   node tools/stamp-build.mjs            stamp dist/
//   node tools/stamp-build.mjs --check    report whether dist/ is stamped, change nothing
//   node tools/stamp-build.mjs --root DIR stamp another copy of dist (used by the cache checks)
//
// What it writes (nothing else is touched):
// - dist/build.js: a content hash per file under dist/assets; code builds asset URLs with assetURL(path). It also
//   reloads the page if it is loaded by a pre-DEPLOY-01 page (no import map), before any game code runs.
// - dist/index.html: the code token (a hash of every .js/.css file and the rest of index.html) in the
//   dustline-build meta tag, the stylesheet URL, the import map that gives every module a ?v=<token> URL, and the
//   start-up check that loads game.js?v=<token> only when the served index.html carries the same token.
// Dot-files (.DS_Store and the like) are ignored everywhere, so they never change the stamp.
// Relative imports inside the modules stay unchanged: the import map versions them, and Node tests import them as is.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const hash = (data, n) => crypto.createHash('sha256').update(data).digest('hex').slice(0, n);
const TOKEN = /^[0-9a-f]{12}$/;
// The stamped parts of index.html, each with exactly one token or generated value.
const REGIONS = [
  {name: 'meta', re: /<meta name="dustline-build" content="([^"]*)">/g},
  {name: 'stylesheet', re: /<link rel="stylesheet" href="style\.css\?v=([^"]*)">/g},
  {name: 'importmap', re: /<script type="importmap">([^<]*)<\/script>/g},
  {name: 'gate', re: /var build = '([^']*)'/g},
];

function listFiles(dir, base = dir) {
  return fs.readdirSync(dir, {withFileTypes: true}).filter(e => !e.name.startsWith('.')).flatMap(e => e.isDirectory() ? listFiles(path.join(dir, e.name), base)
    : [path.relative(base, path.join(dir, e.name)).split(path.sep).join('/')]).sort();
}

export function buildModule(assetVersions) {
  const lines = Object.entries(assetVersions).map(([file, v]) => `  ${JSON.stringify(file)}: ${JSON.stringify(v)},`);
  return `// Generated by tools/stamp-build.mjs; do not edit by hand (DEPLOY-01). A content hash for every bundled asset. Code
// requests assets through assetURL(), so a changed file always gets a new URL and a browser cannot reuse an old copy.
export const ASSET_VERSIONS = {
${lines.join('\n')}
};
export function assetURL(file) { const v = ASSET_VERSIONS[file]; return v ? \`\${file}?v=\${v}\` : file; }
// Loaded without a version by a page from before DEPLOY-01 (no import map, no build stamp): replace that page with the
// current one before any game code runs, instead of mixing its cached modules with this build. Every module changed
// since Build 08 imports this file.
if (typeof location === 'object' && /^https?:$/.test(location.protocol) && !/[?&]v=/.test(import.meta.url) && !document.querySelector('meta[name="dustline-build"]')) {
  location.replace(location.pathname + '?build=upgrade-' + Date.now());
  throw new Error('DUSTLINE: replacing an older cached page with the current build');
}
`;
}

// Everything the stamp would produce for this directory, without writing anything.
export function computeStamp(root) {
  const assetsDir = path.join(root, 'assets');
  const assetVersions = {};
  if (fs.existsSync(assetsDir)) for (const f of listFiles(assetsDir)) assetVersions[`assets/${f}`] = hash(fs.readFileSync(path.join(assetsDir, f)), 10);
  const buildJs = buildModule(assetVersions);
  const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  for (const {name, re} of REGIONS) { const n = [...html.matchAll(re)].length; if (n !== 1) throw new Error(`index.html: expected one stamped ${name}, found ${n}`); }
  const top = fs.readdirSync(root).filter(f => !f.startsWith('.'));
  const modules = top.filter(f => f.endsWith('.js')).concat(fs.existsSync(path.join(root, 'build.js')) ? [] : ['build.js']).sort();
  const code = top.filter(f => /\.(js|css)$/.test(f) && f !== 'build.js').sort();
  // The token covers every code file, the generated build.js and index.html minus its stamped parts.
  const normal = REGIONS.reduce((s, {name, re}) => s.replace(re, `{${name}}`), html);
  const h = crypto.createHash('sha256');
  for (const [name, text] of [...code.map(f => [f, fs.readFileSync(path.join(root, f))]), ['build.js', buildJs], ['index.html', normal]]) h.update(`${name}\0`).update(text).update('\0');
  const token = h.digest('hex').slice(0, 12);
  const importMap = JSON.stringify({imports: Object.fromEntries(modules.map(f => [`./${f}`, `./${f}?v=${token}`]))});
  const stamped = html.replace(REGIONS[0].re, `<meta name="dustline-build" content="${token}">`)
    .replace(REGIONS[1].re, `<link rel="stylesheet" href="style.css?v=${token}">`)
    .replace(REGIONS[2].re, `<script type="importmap">${importMap}</script>`)
    .replace(REGIONS[3].re, `var build = '${token}'`);
  return {token, assetVersions, modules, buildJs, indexHtml: stamped, current: {buildJs: fs.existsSync(path.join(root, 'build.js')) ? fs.readFileSync(path.join(root, 'build.js'), 'utf8') : null, indexHtml: html}};
}

export function stamp(root, {check = false} = {}) {
  const s = computeStamp(root), stale = [];
  if (s.current.buildJs !== s.buildJs) stale.push('build.js');
  if (s.current.indexHtml !== s.indexHtml) stale.push('index.html');
  if (!check) { if (stale.includes('build.js')) fs.writeFileSync(path.join(root, 'build.js'), s.buildJs); if (stale.includes('index.html')) fs.writeFileSync(path.join(root, 'index.html'), s.indexHtml); }
  return {token: s.token, stale, assets: Object.keys(s.assetVersions).length, modules: s.modules.length};
}

const invoked = process.argv[1] && fs.existsSync(process.argv[1]) && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url));
if (invoked) {
  const args = process.argv.slice(2), check = args.includes('--check'), i = args.indexOf('--root');
  if (i >= 0 && (!args[i + 1] || args[i + 1].startsWith('--'))) { console.error('usage: node tools/stamp-build.mjs [--check] [--root DIR]'); process.exit(2); }
  const root = i >= 0 ? path.resolve(args[i + 1]) : path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist');
  const r = stamp(root, {check});
  if (!TOKEN.test(r.token)) throw new Error('bad token');
  if (check) { console.log(r.stale.length ? `NOT STAMPED (${r.stale.join(', ')} out of date); run: node tools/stamp-build.mjs` : `stamped: build ${r.token}`); process.exit(r.stale.length ? 1 : 0); }
  console.log(`${r.stale.length ? 'stamped' : 'already stamped'}: build ${r.token} (${r.modules} modules, ${r.assets} assets${r.stale.length ? '; wrote ' + r.stale.join(', ') : ''})`);
}
